language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install cryptography
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install futures ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install trollius ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install enum34 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install futures ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install trollius ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install enum34 ; fi
  - pip install pycrypto
# command to run tests
script: ./run-tests.sh
